# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  livilmqmicroservice:
    image: livilmqmicroservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5208:5208
    depends_on:
      - "rabbitmq" 

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmqtest"
    labels:
      NAME: "rabbitmqtest"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"